name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Get git short sha
      shell: bash
      run: echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
    - name: Use pnpm
      uses: pnpm/action-setup@v2
      with:
        version: latest
        run_install: false
    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'pnpm'
    - run: pnpm install
    - run: pnpm run build
    - name: Upload build artifact
      uses: actions/upload-artifact@v4.4.3
      with:
        name: build-${{ env.sha_short }}
        path: dist/

  pages:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    concurrency:
      group: 'pages'
      cancel-in-progress: false

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Get git short sha
        shell: bash
        run: echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
      - uses: actions/deploy-pages@v4
        id: deployment
        with:
          artifact_name: build-${{ env.sha_short }}
